# Generated by Django 4.0.2 on 2022-04-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
                ('cUID', models.CharField(default='', max_length=100)),
                ('cpassword', models.CharField(default='', max_length=100)),
                ('cSex', models.CharField(default='M', max_length=2)),
            ],
        ),
    ]
